[package]
name = "whalogen"
version = "0.3.0"
repository = "https://github.com/schang412/typst-whalogen"
entrypoint = "lib.typ"
authors = [
  "Spencer Chang <spencer@sycee.xyz>"
]
categories = [ "layout", "text", "paper" ]
disciplines = [ "education", "chemistry" ]
license = "Apache-2.0"
description = "Typesetting chemical formulae and reactions, a port of mhchem"
exclude = ["manual.pdf", "manual.typ", "gallery/*"]
keywords = ["chemistry", "chemical", "reaction", "formula", "stochiometry", "oxidation", "equation", "electron", "isotope", "molecule", "hazard", "precaution", "h and p", "mhchem"]
